import type { BusinessPlacementVariantDefinition } from "../../types/business";

export const PHASE2A_STARTER_BUSINESS_PLACEMENT_VARIANTS: BusinessPlacementVariantDefinition[] = [
  {
    id: "retail_business:market_shop",
    label: "Market Shop",
    businessTypeId: "market_shop",
    businessNftClassId: "retail_business",
    totalAllocation: 30,
    preferredDistricts: ["neon_market"],
    allowedDistricts: ["neon_market", "cyber_hq"],
    territorySubtypes: ["market_strip", "plaza_edge", "service_row"],
    lotTags: ["retail_frontage", "market_kiosk", "high_traffic", "commercial_corner"],
    lotSize: "small",
    districtLotCounts: {
      neon_market: 22,
      cyber_hq: 8,
    },
  },
  {
    id: "retail_business:streetwear_boutique",
    label: "Streetwear Boutique",
    businessTypeId: "streetwear_boutique",
    businessNftClassId: "retail_business",
    totalAllocation: 20,
    preferredDistricts: ["neon_market"],
    allowedDistricts: ["neon_market", "dark_alley"],
    territorySubtypes: ["plaza_edge", "main_street", "club_row"],
    lotTags: ["retail_frontage", "commercial_corner", "high_traffic", "venue_social"],
    lotSize: "medium",
    districtLotCounts: {
      neon_market: 14,
      dark_alley: 6,
    },
  },
  {
    id: "retail_business:supply_store",
    label: "Supply Store",
    businessTypeId: "supply_store",
    businessNftClassId: "retail_business",
    totalAllocation: 25,
    preferredDistricts: ["neon_market", "cyber_hq"],
    allowedDistricts: ["neon_market", "cyber_hq"],
    territorySubtypes: ["service_row", "market_strip", "industrial_lane"],
    lotTags: ["retail_frontage", "workshop_service", "commercial_corner"],
    lotSize: "medium",
    districtLotCounts: {
      neon_market: 13,
      cyber_hq: 12,
    },
  },
  {
    id: "retail_business:black_market_stall",
    label: "Black Market Stall",
    businessTypeId: "black_market_stall",
    businessNftClassId: "retail_business",
    totalAllocation: 25,
    preferredDistricts: ["dark_alley"],
    allowedDistricts: ["dark_alley"],
    territorySubtypes: ["back_alley", "underground_node"],
    lotTags: ["underground_stall", "low_profile", "covert_access"],
    lotSize: "small",
    districtLotCounts: {
      dark_alley: 25,
    },
  },
  {
    id: "tech_startup:data_hub",
    label: "Data Hub",
    businessTypeId: "data_hub",
    businessNftClassId: "tech_startup",
    totalAllocation: 14,
    preferredDistricts: ["cyber_hq"],
    allowedDistricts: ["cyber_hq", "neon_market"],
    territorySubtypes: ["technical_corridor", "office_block"],
    lotTags: ["office_technical", "office_secure", "intel_node"],
    lotSize: "medium",
    districtLotCounts: {
      cyber_hq: 10,
      neon_market: 4,
    },
  },
  {
    id: "tech_startup:bot_lab",
    label: "Bot Lab",
    businessTypeId: "bot_lab",
    businessNftClassId: "tech_startup",
    totalAllocation: 12,
    preferredDistricts: ["cyber_hq"],
    allowedDistricts: ["cyber_hq"],
    territorySubtypes: ["technical_corridor", "secure_compound"],
    lotTags: ["office_technical", "intel_node", "team_required"],
    lotSize: "medium",
    districtLotCounts: {
      cyber_hq: 12,
    },
  },
  {
    id: "tech_startup:signal_center",
    label: "Signal Center",
    businessTypeId: "signal_center",
    businessNftClassId: "tech_startup",
    totalAllocation: 12,
    preferredDistricts: ["cyber_hq"],
    allowedDistricts: ["cyber_hq", "neon_market"],
    territorySubtypes: ["office_block", "technical_corridor"],
    lotTags: ["office_technical", "intel_node", "high_traffic"],
    lotSize: "medium",
    districtLotCounts: {
      cyber_hq: 8,
      neon_market: 4,
    },
  },
  {
    id: "tech_startup:security_office",
    label: "Security Office",
    businessTypeId: "security_office",
    businessNftClassId: "tech_startup",
    totalAllocation: 12,
    preferredDistricts: ["cyber_hq"],
    allowedDistricts: ["cyber_hq", "neon_market"],
    territorySubtypes: ["secure_compound", "office_block"],
    lotTags: ["office_secure", "district_landmark", "team_required"],
    lotSize: "medium",
    districtLotCounts: {
      cyber_hq: 8,
      neon_market: 4,
    },
  },
  {
    id: "entertainment_venue:club",
    label: "Club",
    businessTypeId: "club",
    businessNftClassId: "entertainment_venue",
    totalAllocation: 20,
    preferredDistricts: ["dark_alley"],
    allowedDistricts: ["dark_alley", "neon_market"],
    territorySubtypes: ["club_row", "back_alley", "plaza_edge"],
    lotTags: ["venue_nightlife", "venue_social", "high_traffic"],
    lotSize: "medium",
    districtLotCounts: {
      dark_alley: 12,
      neon_market: 8,
    },
  },
  {
    id: "entertainment_venue:music_lounge",
    label: "Music Lounge",
    businessTypeId: "music_lounge",
    businessNftClassId: "entertainment_venue",
    totalAllocation: 18,
    preferredDistricts: ["neon_market"],
    allowedDistricts: ["neon_market", "dark_alley"],
    territorySubtypes: ["plaza_edge", "club_row", "main_street"],
    lotTags: ["venue_social", "high_traffic", "commercial_corner"],
    lotSize: "medium",
    districtLotCounts: {
      neon_market: 11,
      dark_alley: 7,
    },
  },
  {
    id: "entertainment_venue:event_hall",
    label: "Event Hall",
    businessTypeId: "event_hall",
    businessNftClassId: "entertainment_venue",
    totalAllocation: 17,
    preferredDistricts: ["neon_market"],
    allowedDistricts: ["neon_market", "cyber_hq"],
    territorySubtypes: ["landmark_corner", "plaza_edge"],
    lotTags: ["district_landmark", "venue_social", "team_required"],
    lotSize: "large",
    districtLotCounts: {
      neon_market: 12,
      cyber_hq: 5,
    },
  },
  {
    id: "entertainment_venue:streaming_studio",
    label: "Streaming Studio",
    businessTypeId: "streaming_studio",
    businessNftClassId: "entertainment_venue",
    totalAllocation: 20,
    preferredDistricts: ["cyber_hq"],
    allowedDistricts: ["cyber_hq", "neon_market"],
    territorySubtypes: ["office_block", "technical_corridor"],
    lotTags: ["office_technical", "venue_social", "intel_node"],
    lotSize: "medium",
    districtLotCounts: {
      cyber_hq: 13,
      neon_market: 7,
    },
  },
  {
    id: "manufacturing_unit:garage",
    label: "Garage",
    businessTypeId: "garage",
    businessNftClassId: "manufacturing_unit",
    totalAllocation: 18,
    preferredDistricts: ["cyber_hq", "neon_market"],
    allowedDistricts: ["cyber_hq", "neon_market"],
    territorySubtypes: ["service_row", "industrial_lane"],
    lotTags: ["workshop_service", "industrial", "commercial_corner"],
    lotSize: "medium",
    districtLotCounts: {
      cyber_hq: 10,
      neon_market: 8,
    },
  },
  {
    id: "manufacturing_unit:repair_shop",
    label: "Repair Shop",
    businessTypeId: "repair_shop",
    businessNftClassId: "manufacturing_unit",
    totalAllocation: 14,
    preferredDistricts: ["neon_market"],
    allowedDistricts: ["neon_market", "cyber_hq"],
    territorySubtypes: ["service_row", "main_street"],
    lotTags: ["workshop_service", "retail_frontage", "high_traffic"],
    lotSize: "medium",
    districtLotCounts: {
      neon_market: 9,
      cyber_hq: 5,
    },
  },
  {
    id: "manufacturing_unit:mod_shop",
    label: "Mod Shop",
    businessTypeId: "mod_shop",
    businessNftClassId: "manufacturing_unit",
    totalAllocation: 14,
    preferredDistricts: ["cyber_hq"],
    allowedDistricts: ["cyber_hq", "neon_market"],
    territorySubtypes: ["technical_corridor", "industrial_lane"],
    lotTags: ["workshop_service", "office_technical", "team_required"],
    lotSize: "medium",
    districtLotCounts: {
      cyber_hq: 9,
      neon_market: 5,
    },
  },
  {
    id: "manufacturing_unit:workshop",
    label: "Workshop",
    businessTypeId: "workshop",
    businessNftClassId: "manufacturing_unit",
    totalAllocation: 14,
    preferredDistricts: ["cyber_hq"],
    allowedDistricts: ["cyber_hq", "dark_alley"],
    territorySubtypes: ["industrial_lane", "secure_compound"],
    lotTags: ["industrial_production", "team_required", "low_profile"],
    lotSize: "large",
    districtLotCounts: {
      cyber_hq: 10,
      dark_alley: 4,
    },
  },
  {
    id: "financial_institution:bank_branch",
    label: "Bank Branch",
    businessTypeId: "bank_branch",
    businessNftClassId: "financial_institution",
    totalAllocation: 10,
    preferredDistricts: ["neon_market"],
    allowedDistricts: ["neon_market", "cyber_hq"],
    territorySubtypes: ["main_street", "landmark_corner"],
    lotTags: ["financial_secure", "commercial_corner", "high_traffic"],
    lotSize: "medium",
    districtLotCounts: {
      neon_market: 6,
      cyber_hq: 4,
    },
  },
  {
    id: "financial_institution:exchange_desk",
    label: "Exchange Desk",
    businessTypeId: "exchange_desk",
    businessNftClassId: "financial_institution",
    totalAllocation: 10,
    preferredDistricts: ["neon_market"],
    allowedDistricts: ["neon_market", "cyber_hq"],
    territorySubtypes: ["market_strip", "office_block"],
    lotTags: ["financial_secure", "high_traffic", "intel_node"],
    lotSize: "medium",
    districtLotCounts: {
      neon_market: 6,
      cyber_hq: 4,
    },
  },
  {
    id: "financial_institution:treasury_office",
    label: "Treasury Office",
    businessTypeId: "treasury_office",
    businessNftClassId: "financial_institution",
    totalAllocation: 10,
    preferredDistricts: ["cyber_hq"],
    allowedDistricts: ["cyber_hq"],
    territorySubtypes: ["secure_compound", "office_block"],
    lotTags: ["financial_secure", "district_landmark", "team_required"],
    lotSize: "large",
    districtLotCounts: {
      cyber_hq: 10,
    },
  },
  {
    id: "financial_institution:lending_hall",
    label: "Lending Hall",
    businessTypeId: "lending_hall",
    businessNftClassId: "financial_institution",
    totalAllocation: 10,
    preferredDistricts: ["neon_market", "cyber_hq"],
    allowedDistricts: ["neon_market", "cyber_hq"],
    territorySubtypes: ["main_street", "office_block"],
    lotTags: ["financial_secure", "commercial_corner", "team_required"],
    lotSize: "medium",
    districtLotCounts: {
      neon_market: 5,
      cyber_hq: 5,
    },
  },
];

for (const variant of PHASE2A_STARTER_BUSINESS_PLACEMENT_VARIANTS) {
  const totalLots = Object.values(variant.districtLotCounts).reduce(
    (sum, count) => sum + (count ?? 0),
    0
  );

  if (totalLots !== variant.totalAllocation) {
    throw new Error(
      `Invalid lot distribution for ${variant.id}: expected ${variant.totalAllocation}, received ${totalLots}.`
    );
  }
}
