import type { NerdieCityDistrict } from "./types";
import type {
  BusinessDistrictRule,
  BusinessEligibilityDefinition,
  BusinessNftClassDefinition,
  BusinessPermissionId,
  BusinessStakingTier,
  BusinessStakingTierDefinition,
  PlayableBusinessBridgeDefinition,
} from "../../types/business";

export const BUSINESS_STAKING_TIER_ORDER: BusinessStakingTier[] = [
  "none",
  "starter_business",
  "district_operator",
  "city_operator",
];

export const PHASE1_BUSINESS_STAKING_TIERS: Record<
  BusinessStakingTier,
  BusinessStakingTierDefinition
> = {
  none: {
    tier: "none",
    label: "Unstaked",
    description: "No active staking entitlement for business rights.",
  },
  starter_business: {
    tier: "starter_business",
    label: "Starter Business Stake",
    description: "Represents a basic business-license or operator stake for entry-level shops and services.",
  },
  district_operator: {
    tier: "district_operator",
    label: "District Operator Stake",
    description: "Represents the added district pass or district license stake needed for district-sensitive operations.",
  },
  city_operator: {
    tier: "city_operator",
    label: "City Operator Stake",
    description: "Reserved for future higher-capacity city businesses and strategic nodes.",
  },
};

export const PHASE1_DISTRICT_BUSINESS_RULES: Record<
  NerdieCityDistrict,
  BusinessDistrictRule
> = {
  neon_market: {
    district: "neon_market",
    preferredSectors: ["retail", "racing_mechanical"],
    riskProfile: "medium",
  },
  dark_alley: {
    district: "dark_alley",
    preferredSectors: ["black_market_underground"],
    riskProfile: "high",
  },
  cyber_hq: {
    district: "cyber_hq",
    preferredSectors: ["technology", "racing_mechanical"],
    riskProfile: "strategic",
  },
};

const DISTRICT_ACCESS_PERMISSIONS: Record<NerdieCityDistrict, BusinessPermissionId> = {
  neon_market: "district_neon_market_access",
  dark_alley: "district_dark_alley_access",
  cyber_hq: "district_cyber_hq_access",
};

export const PHASE1_BUSINESS_NFT_CLASSES: BusinessNftClassDefinition[] = [
  {
    id: "retail_business",
    tokenId: 1,
    name: "Retail Business",
    mintPriceEth: 0.01,
    dailyRewardTokens: 120,
    opensBusinessTypes: ["market_shop"],
    preferredDistricts: ["neon_market"],
    grantedPermissions: ["open_market_shop", "public_commerce_ops", "district_neon_market_access"],
    summary: "Phase 1 retail ownership that cleanly maps into public storefront play in Neon Market.",
  },
  {
    id: "tech_startup",
    tokenId: 2,
    name: "Tech Startup",
    mintPriceEth: 0.015,
    dailyRewardTokens: 150,
    opensBusinessTypes: ["data_hub", "garage"],
    preferredDistricts: ["cyber_hq"],
    grantedPermissions: ["open_data_hub", "open_garage", "technical_service_ops", "district_cyber_hq_access"],
    summary: "Technical operator class that bridges data services first and garage-style service play second.",
  },
  {
    id: "entertainment_venue",
    tokenId: 3,
    name: "Entertainment Venue",
    mintPriceEth: 0.012,
    dailyRewardTokens: 140,
    opensBusinessTypes: ["market_shop"],
    preferredDistricts: ["neon_market", "dark_alley"],
    grantedPermissions: ["open_market_shop", "public_commerce_ops", "district_neon_market_access", "district_dark_alley_access"],
    summary: "Phase 1 consumer-facing venue class that temporarily maps into storefront-style business play.",
  },
  {
    id: "manufacturing_unit",
    tokenId: 4,
    name: "Manufacturing Unit",
    mintPriceEth: 0.02,
    dailyRewardTokens: 180,
    opensBusinessTypes: ["garage"],
    preferredDistricts: ["cyber_hq", "neon_market"],
    grantedPermissions: ["open_garage", "technical_service_ops", "district_cyber_hq_access", "district_neon_market_access"],
    summary: "Production-focused business class that currently maps into mechanical and service-heavy starter operations.",
  },
  {
    id: "financial_institution",
    tokenId: 5,
    name: "Financial Institution",
    mintPriceEth: 0.025,
    dailyRewardTokens: 200,
    opensBusinessTypes: ["data_hub", "black_market_stall"],
    preferredDistricts: ["cyber_hq", "dark_alley"],
    grantedPermissions: ["open_data_hub", "open_black_market_stall", "underground_trade_ops", "district_cyber_hq_access", "district_dark_alley_access"],
    summary: "Higher-trust capital and intel class that maps into data and underground commerce play in Phase 1.",
  },
];

export const PHASE1_PLAYABLE_BUSINESS_BRIDGES: PlayableBusinessBridgeDefinition[] = [
  {
    businessTypeId: "market_shop",
    compatibleBusinessNftClasses: ["retail_business", "entertainment_venue"],
    grantedPermissions: ["open_market_shop", "public_commerce_ops", DISTRICT_ACCESS_PERMISSIONS.neon_market],
  },
  {
    businessTypeId: "garage",
    compatibleBusinessNftClasses: ["tech_startup", "manufacturing_unit"],
    grantedPermissions: ["open_garage", "technical_service_ops", DISTRICT_ACCESS_PERMISSIONS.cyber_hq],
  },
  {
    businessTypeId: "data_hub",
    compatibleBusinessNftClasses: ["tech_startup", "financial_institution"],
    grantedPermissions: ["open_data_hub", "technical_service_ops", DISTRICT_ACCESS_PERMISSIONS.cyber_hq],
  },
  {
    businessTypeId: "black_market_stall",
    compatibleBusinessNftClasses: ["financial_institution"],
    grantedPermissions: ["open_black_market_stall", "underground_trade_ops", DISTRICT_ACCESS_PERMISSIONS.dark_alley],
  },
];

export const PHASE1_BUSINESS_ELIGIBILITY_DEFINITIONS: BusinessEligibilityDefinition[] = [
  {
    id: "market_shop",
    name: "Market Shop",
    sector: "retail",
    requiresBusinessNft: true,
    minLevel: 25,
    minimumRankTier: "bronze",
    minimumReputationScore: 100,
    maximumHeatScore: 50,
    requiredStakingTier: "starter_business",
    requiredMilestones: ["business_eligibility_baseline"],
    allowedDistricts: ["neon_market", "cyber_hq"],
    preferredDistricts: ["neon_market"],
    recommendedRoles: ["trader", "data_broker"],
    requiredCertificationMissionIds: [],
    teamSlots: {
      owner: {
        kind: "owner",
        totalSlots: 1,
        requiredSlots: 1,
        preferredRoles: ["trader"],
        label: "Owner Slot",
      },
      operators: {
        kind: "operator",
        totalSlots: 1,
        requiredSlots: 1,
        preferredRoles: ["trader", "data_broker"],
        label: "Operator Slots",
      },
      support: {
        kind: "support",
        totalSlots: 1,
        requiredSlots: 0,
        preferredRoles: ["data_broker"],
        label: "Support Slots",
      },
    },
    defenseSlots: {
      guardBots: {
        kind: "guard_bot",
        totalSlots: 1,
        requiredSlots: 0,
        preferredRoles: ["code_warrior"],
        label: "Guard Bot Slots",
      },
      securityModules: {
        kind: "security_module",
        totalSlots: 1,
        requiredSlots: 0,
        preferredRoles: ["data_broker"],
        label: "Security Module Slots",
      },
      protectionRoles: {
        kind: "protection_role",
        totalSlots: 1,
        requiredSlots: 0,
        preferredRoles: ["trader", "code_warrior"],
        label: "Protection Role Slots",
      },
    },
    trustPolicy: {
      minimumDistrictTrustBandForHigherTrustOps: "known",
      minimumDistrictTrustBandForDefensePermissions: "known",
      minimumDistrictTrustBandForAdvancedOperatorAccess: "trusted",
      certificationMissionIdsForHigherTrustOps: [],
      certificationMissionIdsForDefensePermissions: [],
      certificationMissionIdsForAdvancedOperatorAccess: [],
    },
  },
  {
    id: "garage",
    name: "Garage",
    sector: "racing_mechanical",
    requiresBusinessNft: true,
    minLevel: 25,
    minimumRankTier: "silver",
    minimumReputationScore: 100,
    maximumHeatScore: 60,
    requiredStakingTier: "starter_business",
    requiredMilestones: ["business_eligibility_baseline"],
    allowedDistricts: ["neon_market", "cyber_hq"],
    preferredDistricts: ["cyber_hq", "neon_market"],
    recommendedRoles: ["code_warrior", "trader"],
    requiredCertificationMissionIds: [],
    teamSlots: {
      owner: {
        kind: "owner",
        totalSlots: 1,
        requiredSlots: 1,
        preferredRoles: ["code_warrior"],
        label: "Owner Slot",
      },
      operators: {
        kind: "operator",
        totalSlots: 2,
        requiredSlots: 1,
        preferredRoles: ["code_warrior", "trader"],
        label: "Operator Slots",
      },
      support: {
        kind: "support",
        totalSlots: 2,
        requiredSlots: 0,
        preferredRoles: ["trader", "data_broker"],
        label: "Support Slots",
      },
    },
    defenseSlots: {
      guardBots: {
        kind: "guard_bot",
        totalSlots: 1,
        requiredSlots: 0,
        preferredRoles: ["code_warrior"],
        label: "Guard Bot Slots",
      },
      securityModules: {
        kind: "security_module",
        totalSlots: 1,
        requiredSlots: 0,
        preferredRoles: ["code_warrior"],
        label: "Security Module Slots",
      },
      protectionRoles: {
        kind: "protection_role",
        totalSlots: 1,
        requiredSlots: 0,
        preferredRoles: ["trader", "code_warrior"],
        label: "Protection Role Slots",
      },
    },
    trustPolicy: {
      minimumDistrictTrustBandForHigherTrustOps: "known",
      minimumDistrictTrustBandForDefensePermissions: "trusted",
      minimumDistrictTrustBandForAdvancedOperatorAccess: "trusted",
      certificationMissionIdsForHigherTrustOps: [],
      certificationMissionIdsForDefensePermissions: [],
      certificationMissionIdsForAdvancedOperatorAccess: [],
    },
  },
  {
    id: "data_hub",
    name: "Data Hub",
    sector: "technology",
    requiresBusinessNft: true,
    minLevel: 25,
    minimumRankTier: "silver",
    minimumReputationScore: 250,
    maximumHeatScore: 40,
    requiredStakingTier: "district_operator",
    requiredMilestones: ["business_eligibility_baseline", "district_privilege_tier_1"],
    allowedDistricts: ["cyber_hq", "neon_market"],
    preferredDistricts: ["cyber_hq"],
    recommendedRoles: ["data_broker", "code_warrior"],
    requiredCertificationMissionIds: ["beginner-defi-certification"],
    teamSlots: {
      owner: {
        kind: "owner",
        totalSlots: 1,
        requiredSlots: 1,
        preferredRoles: ["data_broker"],
        label: "Owner Slot",
      },
      operators: {
        kind: "operator",
        totalSlots: 2,
        requiredSlots: 2,
        preferredRoles: ["data_broker", "code_warrior"],
        label: "Operator Slots",
      },
      support: {
        kind: "support",
        totalSlots: 2,
        requiredSlots: 0,
        preferredRoles: ["code_warrior", "trader"],
        label: "Support Slots",
      },
    },
    defenseSlots: {
      guardBots: {
        kind: "guard_bot",
        totalSlots: 1,
        requiredSlots: 0,
        preferredRoles: ["code_warrior"],
        label: "Guard Bot Slots",
      },
      securityModules: {
        kind: "security_module",
        totalSlots: 2,
        requiredSlots: 0,
        preferredRoles: ["data_broker", "code_warrior"],
        label: "Security Module Slots",
      },
      protectionRoles: {
        kind: "protection_role",
        totalSlots: 1,
        requiredSlots: 0,
        preferredRoles: ["data_broker", "code_warrior"],
        label: "Protection Role Slots",
      },
    },
    trustPolicy: {
      minimumDistrictTrustBandForHigherTrustOps: "trusted",
      minimumDistrictTrustBandForDefensePermissions: "trusted",
      minimumDistrictTrustBandForAdvancedOperatorAccess: "elevated",
      certificationMissionIdsForHigherTrustOps: ["beginner-defi-certification"],
      certificationMissionIdsForDefensePermissions: ["beginner-defi-certification"],
      certificationMissionIdsForAdvancedOperatorAccess: ["beginner-defi-certification"],
    },
  },
  {
    id: "black_market_stall",
    name: "Black Market Stall",
    sector: "black_market_underground",
    requiresBusinessNft: true,
    minLevel: 25,
    minimumRankTier: "gold",
    minimumReputationScore: 250,
    maximumHeatScore: null,
    requiredStakingTier: "district_operator",
    requiredMilestones: ["business_eligibility_baseline", "district_privilege_tier_1"],
    allowedDistricts: ["dark_alley"],
    preferredDistricts: ["dark_alley"],
    recommendedRoles: ["hacker", "data_broker"],
    requiredCertificationMissionIds: [],
    teamSlots: {
      owner: {
        kind: "owner",
        totalSlots: 1,
        requiredSlots: 1,
        preferredRoles: ["hacker"],
        label: "Owner Slot",
      },
      operators: {
        kind: "operator",
        totalSlots: 2,
        requiredSlots: 2,
        preferredRoles: ["hacker", "data_broker"],
        label: "Operator Slots",
      },
      support: {
        kind: "support",
        totalSlots: 1,
        requiredSlots: 0,
        preferredRoles: ["data_broker"],
        label: "Support Slots",
      },
    },
    defenseSlots: {
      guardBots: {
        kind: "guard_bot",
        totalSlots: 2,
        requiredSlots: 0,
        preferredRoles: ["hacker"],
        label: "Guard Bot Slots",
      },
      securityModules: {
        kind: "security_module",
        totalSlots: 1,
        requiredSlots: 0,
        preferredRoles: ["data_broker"],
        label: "Security Module Slots",
      },
      protectionRoles: {
        kind: "protection_role",
        totalSlots: 2,
        requiredSlots: 0,
        preferredRoles: ["hacker", "data_broker"],
        label: "Protection Role Slots",
      },
    },
    trustPolicy: {
      minimumDistrictTrustBandForHigherTrustOps: "trusted",
      minimumDistrictTrustBandForDefensePermissions: "elevated",
      minimumDistrictTrustBandForAdvancedOperatorAccess: "elevated",
      certificationMissionIdsForHigherTrustOps: [],
      certificationMissionIdsForDefensePermissions: [],
      certificationMissionIdsForAdvancedOperatorAccess: [],
    },
  },
];
