import type { NerdieCityDistrict, NerdieCityRole } from "./types";
import type {
  BusinessDistrictRule,
  BusinessEligibilityDefinition,
  BusinessNftClassDefinition,
  BusinessPermissionId,
  BusinessStakingTier,
  BusinessStakingTierDefinition,
  DistrictTrustBand,
  PlayableBusinessBridgeDefinition,
} from "../../types/business";

export const BUSINESS_STAKING_TIER_ORDER: BusinessStakingTier[] = [
  "none",
  "starter_business",
  "district_operator",
  "city_operator",
];

export const PHASE1_BUSINESS_STAKING_TIERS: Record<
  BusinessStakingTier,
  BusinessStakingTierDefinition
> = {
  none: {
    tier: "none",
    label: "Unstaked",
    description: "No active staking entitlement for business rights.",
  },
  starter_business: {
    tier: "starter_business",
    label: "Starter Business Stake",
    description: "Represents a basic business-license or operator stake for entry-level shops and services.",
  },
  district_operator: {
    tier: "district_operator",
    label: "District Operator Stake",
    description: "Represents the added district pass or district license stake needed for district-sensitive operations.",
  },
  city_operator: {
    tier: "city_operator",
    label: "City Operator Stake",
    description: "Reserved for future higher-capacity city businesses and strategic nodes.",
  },
};

export const PHASE1_DISTRICT_BUSINESS_RULES: Record<
  NerdieCityDistrict,
  BusinessDistrictRule
> = {
  neon_market: {
    district: "neon_market",
    preferredSectors: ["retail_business", "entertainment_venue", "financial_institution"],
    riskProfile: "medium",
  },
  dark_alley: {
    district: "dark_alley",
    preferredSectors: ["retail_business", "entertainment_venue"],
    riskProfile: "high",
  },
  cyber_hq: {
    district: "cyber_hq",
    preferredSectors: ["tech_startup", "manufacturing_unit", "financial_institution"],
    riskProfile: "strategic",
  },
};

const DISTRICT_ACCESS_PERMISSIONS: Record<NerdieCityDistrict, BusinessPermissionId> = {
  neon_market: "district_neon_market_access",
  dark_alley: "district_dark_alley_access",
  cyber_hq: "district_cyber_hq_access",
};

function buildTeamSlots(
  ownerRoles: NerdieCityRole[],
  operatorRoles: NerdieCityRole[],
  operatorRequired: number,
  operatorTotal: number,
  supportRoles: NerdieCityRole[],
  supportRequired: number,
  supportTotal: number
) {
  return {
    owner: {
      kind: "owner" as const,
      totalSlots: 1,
      requiredSlots: 1,
      preferredRoles: ownerRoles,
      label: "Owner Slot",
    },
    operators: {
      kind: "operator" as const,
      totalSlots: operatorTotal,
      requiredSlots: operatorRequired,
      preferredRoles: operatorRoles,
      label: "Operator Slots",
    },
    support: {
      kind: "support" as const,
      totalSlots: supportTotal,
      requiredSlots: supportRequired,
      preferredRoles: supportRoles,
      label: "Support Slots",
    },
  };
}

function buildDefenseSlots(
  guardTotal: number,
  guardRequired: number,
  securityTotal: number,
  securityRequired: number,
  protectionTotal: number,
  protectionRequired: number,
  securityRoles: NerdieCityRole[] = ["code_warrior", "data_broker"],
  protectionRoles: NerdieCityRole[] = ["trader", "code_warrior"],
  guardRoles: NerdieCityRole[] = ["code_warrior"]
) {
  return {
    guardBots: {
      kind: "guard_bot" as const,
      totalSlots: guardTotal,
      requiredSlots: guardRequired,
      preferredRoles: guardRoles,
      label: "Guard Bot Slots",
    },
    securityModules: {
      kind: "security_module" as const,
      totalSlots: securityTotal,
      requiredSlots: securityRequired,
      preferredRoles: securityRoles,
      label: "Security Module Slots",
    },
    protectionRoles: {
      kind: "protection_role" as const,
      totalSlots: protectionTotal,
      requiredSlots: protectionRequired,
      preferredRoles: protectionRoles,
      label: "Protection Role Slots",
    },
  };
}

function buildTrustPolicy(
  higherTrustBand: DistrictTrustBand,
  defenseBand: DistrictTrustBand,
  advancedBand: DistrictTrustBand,
  certificationMissionIdsForHigherTrustOps: BusinessEligibilityDefinition["requiredCertificationMissionIds"] = [],
  certificationMissionIdsForDefensePermissions: BusinessEligibilityDefinition["requiredCertificationMissionIds"] = [],
  certificationMissionIdsForAdvancedOperatorAccess: BusinessEligibilityDefinition["requiredCertificationMissionIds"] = []
) {
  return {
    minimumDistrictTrustBandForHigherTrustOps: higherTrustBand,
    minimumDistrictTrustBandForDefensePermissions: defenseBand,
    minimumDistrictTrustBandForAdvancedOperatorAccess: advancedBand,
    certificationMissionIdsForHigherTrustOps,
    certificationMissionIdsForDefensePermissions,
    certificationMissionIdsForAdvancedOperatorAccess,
  };
}

type VariantDefinitionInput = Omit<
  BusinessEligibilityDefinition,
  "teamSlots" | "defenseSlots" | "trustPolicy"
> & {
  team: Parameters<typeof buildTeamSlots>;
  defense: Parameters<typeof buildDefenseSlots>;
  trust: Parameters<typeof buildTrustPolicy>;
};

function defineBusinessVariant(input: VariantDefinitionInput): BusinessEligibilityDefinition {
  return {
    id: input.id,
    name: input.name,
    sector: input.sector,
    requiresBusinessNft: input.requiresBusinessNft,
    minLevel: input.minLevel,
    minimumRankTier: input.minimumRankTier,
    minimumReputationScore: input.minimumReputationScore,
    maximumHeatScore: input.maximumHeatScore,
    requiredStakingTier: input.requiredStakingTier,
    requiredMilestones: input.requiredMilestones,
    allowedDistricts: input.allowedDistricts,
    preferredDistricts: input.preferredDistricts,
    recommendedRoles: input.recommendedRoles,
    requiredCertificationMissionIds: input.requiredCertificationMissionIds,
    requiredActivationCertificationMissionIds:
      input.requiredActivationCertificationMissionIds,
    teamSlots: buildTeamSlots(...input.team),
    defenseSlots: buildDefenseSlots(...input.defense),
    trustPolicy: buildTrustPolicy(...input.trust),
  };
}

function buildClassSummary(
  name: string,
  opensBusinessTypes: string[],
  sectorSummary: string
) {
  return `${name} is the ownership source for ${opensBusinessTypes.join(", ")}, with ${sectorSummary}`;
}

export const PHASE1_BUSINESS_NFT_CLASSES: BusinessNftClassDefinition[] = [
  {
    id: "retail_business",
    tokenId: 1,
    name: "Retail Business",
    mintPriceEth: 0.01,
    dailyRewardTokens: 120,
    opensBusinessTypes: [
      "market_shop",
      "streetwear_boutique",
      "supply_store",
      "black_market_stall",
    ],
    preferredDistricts: ["neon_market", "dark_alley", "cyber_hq"],
    grantedPermissions: [
      "open_market_shop",
      "open_streetwear_boutique",
      "open_supply_store",
      "open_black_market_stall",
      "public_commerce_ops",
      "underground_trade_ops",
      "district_neon_market_access",
      "district_dark_alley_access",
      "district_cyber_hq_access",
    ],
    summary: buildClassSummary(
      "Retail Business",
      ["Market Shop", "Streetwear Boutique", "Supply Store", "Black Market Stall"],
      "public commerce in Neon Market, utility supply in Cyber HQ, and underground retail in Dark Alley."
    ),
  },
  {
    id: "tech_startup",
    tokenId: 2,
    name: "Tech Startup",
    mintPriceEth: 0.015,
    dailyRewardTokens: 150,
    opensBusinessTypes: ["data_hub", "bot_lab", "signal_center", "security_office"],
    preferredDistricts: ["cyber_hq", "neon_market"],
    grantedPermissions: [
      "open_data_hub",
      "open_bot_lab",
      "open_signal_center",
      "open_security_office",
      "technical_service_ops",
      "district_cyber_hq_access",
      "district_neon_market_access",
    ],
    summary: buildClassSummary(
      "Tech Startup",
      ["Data Hub", "Bot Lab", "Signal Center", "Security Office"],
      "technical operations clustered around Cyber HQ with limited Neon Market spillover."
    ),
  },
  {
    id: "entertainment_venue",
    tokenId: 3,
    name: "Entertainment Venue",
    mintPriceEth: 0.012,
    dailyRewardTokens: 140,
    opensBusinessTypes: ["club", "music_lounge", "event_hall", "streaming_studio"],
    preferredDistricts: ["neon_market", "dark_alley", "cyber_hq"],
    grantedPermissions: [
      "open_club",
      "open_music_lounge",
      "open_event_hall",
      "open_streaming_studio",
      "entertainment_ops",
      "district_neon_market_access",
      "district_dark_alley_access",
      "district_cyber_hq_access",
    ],
    summary: buildClassSummary(
      "Entertainment Venue",
      ["Club", "Music Lounge", "Event Hall", "Streaming Studio"],
      "social and media operations split across nightlife, public foot traffic, and content production spaces."
    ),
  },
  {
    id: "manufacturing_unit",
    tokenId: 4,
    name: "Manufacturing Unit",
    mintPriceEth: 0.02,
    dailyRewardTokens: 180,
    opensBusinessTypes: ["garage", "repair_shop", "mod_shop", "workshop"],
    preferredDistricts: ["cyber_hq", "neon_market", "dark_alley"],
    grantedPermissions: [
      "open_garage",
      "open_repair_shop",
      "open_mod_shop",
      "open_workshop",
      "manufacturing_ops",
      "district_cyber_hq_access",
      "district_neon_market_access",
      "district_dark_alley_access",
    ],
    summary: buildClassSummary(
      "Manufacturing Unit",
      ["Garage", "Repair Shop", "Mod Shop", "Workshop"],
      "service-heavy technical and mechanical production with future defense and logistics hooks."
    ),
  },
  {
    id: "financial_institution",
    tokenId: 5,
    name: "Financial Institution",
    mintPriceEth: 0.025,
    dailyRewardTokens: 200,
    opensBusinessTypes: ["bank_branch", "exchange_desk", "treasury_office", "lending_hall"],
    preferredDistricts: ["neon_market", "cyber_hq"],
    grantedPermissions: [
      "open_bank_branch",
      "open_exchange_desk",
      "open_treasury_office",
      "open_lending_hall",
      "financial_ops",
      "district_neon_market_access",
      "district_cyber_hq_access",
    ],
    summary: buildClassSummary(
      "Financial Institution",
      ["Bank Branch", "Exchange Desk", "Treasury Office", "Lending Hall"],
      "capital, treasury, and exchange operations with stronger trust and staking expectations."
    ),
  },
];

export const PHASE1_PLAYABLE_BUSINESS_BRIDGES: PlayableBusinessBridgeDefinition[] = [
  {
    businessTypeId: "market_shop",
    compatibleBusinessNftClasses: ["retail_business"],
    grantedPermissions: ["open_market_shop", "public_commerce_ops", DISTRICT_ACCESS_PERMISSIONS.neon_market],
  },
  {
    businessTypeId: "streetwear_boutique",
    compatibleBusinessNftClasses: ["retail_business"],
    grantedPermissions: ["open_streetwear_boutique", "public_commerce_ops", DISTRICT_ACCESS_PERMISSIONS.neon_market],
  },
  {
    businessTypeId: "supply_store",
    compatibleBusinessNftClasses: ["retail_business"],
    grantedPermissions: ["open_supply_store", "public_commerce_ops", DISTRICT_ACCESS_PERMISSIONS.cyber_hq],
  },
  {
    businessTypeId: "black_market_stall",
    compatibleBusinessNftClasses: ["retail_business"],
    grantedPermissions: ["open_black_market_stall", "underground_trade_ops", DISTRICT_ACCESS_PERMISSIONS.dark_alley],
  },
  {
    businessTypeId: "data_hub",
    compatibleBusinessNftClasses: ["tech_startup"],
    grantedPermissions: ["open_data_hub", "technical_service_ops", DISTRICT_ACCESS_PERMISSIONS.cyber_hq],
  },
  {
    businessTypeId: "bot_lab",
    compatibleBusinessNftClasses: ["tech_startup"],
    grantedPermissions: ["open_bot_lab", "technical_service_ops", DISTRICT_ACCESS_PERMISSIONS.cyber_hq],
  },
  {
    businessTypeId: "signal_center",
    compatibleBusinessNftClasses: ["tech_startup"],
    grantedPermissions: ["open_signal_center", "technical_service_ops", DISTRICT_ACCESS_PERMISSIONS.cyber_hq],
  },
  {
    businessTypeId: "security_office",
    compatibleBusinessNftClasses: ["tech_startup"],
    grantedPermissions: ["open_security_office", "technical_service_ops", DISTRICT_ACCESS_PERMISSIONS.cyber_hq],
  },
  {
    businessTypeId: "club",
    compatibleBusinessNftClasses: ["entertainment_venue"],
    grantedPermissions: ["open_club", "entertainment_ops", DISTRICT_ACCESS_PERMISSIONS.dark_alley],
  },
  {
    businessTypeId: "music_lounge",
    compatibleBusinessNftClasses: ["entertainment_venue"],
    grantedPermissions: ["open_music_lounge", "entertainment_ops", DISTRICT_ACCESS_PERMISSIONS.neon_market],
  },
  {
    businessTypeId: "event_hall",
    compatibleBusinessNftClasses: ["entertainment_venue"],
    grantedPermissions: ["open_event_hall", "entertainment_ops", DISTRICT_ACCESS_PERMISSIONS.neon_market],
  },
  {
    businessTypeId: "streaming_studio",
    compatibleBusinessNftClasses: ["entertainment_venue"],
    grantedPermissions: ["open_streaming_studio", "entertainment_ops", DISTRICT_ACCESS_PERMISSIONS.cyber_hq],
  },
  {
    businessTypeId: "garage",
    compatibleBusinessNftClasses: ["manufacturing_unit"],
    grantedPermissions: ["open_garage", "manufacturing_ops", DISTRICT_ACCESS_PERMISSIONS.cyber_hq],
  },
  {
    businessTypeId: "repair_shop",
    compatibleBusinessNftClasses: ["manufacturing_unit"],
    grantedPermissions: ["open_repair_shop", "manufacturing_ops", DISTRICT_ACCESS_PERMISSIONS.neon_market],
  },
  {
    businessTypeId: "mod_shop",
    compatibleBusinessNftClasses: ["manufacturing_unit"],
    grantedPermissions: ["open_mod_shop", "manufacturing_ops", DISTRICT_ACCESS_PERMISSIONS.cyber_hq],
  },
  {
    businessTypeId: "workshop",
    compatibleBusinessNftClasses: ["manufacturing_unit"],
    grantedPermissions: ["open_workshop", "manufacturing_ops", DISTRICT_ACCESS_PERMISSIONS.cyber_hq],
  },
  {
    businessTypeId: "bank_branch",
    compatibleBusinessNftClasses: ["financial_institution"],
    grantedPermissions: ["open_bank_branch", "financial_ops", DISTRICT_ACCESS_PERMISSIONS.neon_market],
  },
  {
    businessTypeId: "exchange_desk",
    compatibleBusinessNftClasses: ["financial_institution"],
    grantedPermissions: ["open_exchange_desk", "financial_ops", DISTRICT_ACCESS_PERMISSIONS.neon_market],
  },
  {
    businessTypeId: "treasury_office",
    compatibleBusinessNftClasses: ["financial_institution"],
    grantedPermissions: ["open_treasury_office", "financial_ops", DISTRICT_ACCESS_PERMISSIONS.cyber_hq],
  },
  {
    businessTypeId: "lending_hall",
    compatibleBusinessNftClasses: ["financial_institution"],
    grantedPermissions: ["open_lending_hall", "financial_ops", DISTRICT_ACCESS_PERMISSIONS.cyber_hq],
  },
];

const BASIC_MILESTONES = ["business_eligibility_baseline"];
const DISTRICT_MILESTONES = ["business_eligibility_baseline", "district_privilege_tier_1"];
const ADVANCED_MILESTONES = [
  "business_eligibility_baseline",
  "district_privilege_tier_1",
  "district_privilege_tier_2",
];
const DEFI_CERTS = ["beginner-defi-certification"];
const OPERATOR_ACTIVATION_CERTS = ["business-operator-staking-certification"];

export const PHASE1_BUSINESS_ELIGIBILITY_DEFINITIONS: BusinessEligibilityDefinition[] = [
  defineBusinessVariant({
    id: "market_shop",
    name: "Market Shop",
    sector: "retail_business",
    requiresBusinessNft: true,
    minLevel: 25,
    minimumRankTier: "bronze",
    minimumReputationScore: 100,
    maximumHeatScore: 50,
    requiredStakingTier: "starter_business",
    requiredMilestones: BASIC_MILESTONES,
    allowedDistricts: ["neon_market", "cyber_hq"],
    preferredDistricts: ["neon_market"],
    recommendedRoles: ["trader", "data_broker"],
    requiredCertificationMissionIds: [],
    requiredActivationCertificationMissionIds: OPERATOR_ACTIVATION_CERTS,
    team: [["trader"], ["trader", "data_broker"], 1, 1, ["data_broker"], 0, 1],
    defense: [1, 0, 1, 0, 1, 0],
    trust: ["known", "known", "trusted"],
  }),
  defineBusinessVariant({
    id: "streetwear_boutique",
    name: "Streetwear Boutique",
    sector: "retail_business",
    requiresBusinessNft: true,
    minLevel: 28,
    minimumRankTier: "silver",
    minimumReputationScore: 140,
    maximumHeatScore: 45,
    requiredStakingTier: "district_operator",
    requiredMilestones: DISTRICT_MILESTONES,
    allowedDistricts: ["neon_market", "dark_alley"],
    preferredDistricts: ["neon_market"],
    recommendedRoles: ["trader", "data_broker"],
    requiredCertificationMissionIds: [],
    requiredActivationCertificationMissionIds: OPERATOR_ACTIVATION_CERTS,
    team: [["trader"], ["trader", "data_broker"], 2, 2, ["data_broker"], 0, 2],
    defense: [1, 0, 1, 0, 2, 0],
    trust: ["trusted", "trusted", "elevated"],
  }),
  defineBusinessVariant({
    id: "supply_store",
    name: "Supply Store",
    sector: "retail_business",
    requiresBusinessNft: true,
    minLevel: 26,
    minimumRankTier: "bronze",
    minimumReputationScore: 110,
    maximumHeatScore: 55,
    requiredStakingTier: "starter_business",
    requiredMilestones: BASIC_MILESTONES,
    allowedDistricts: ["neon_market", "cyber_hq"],
    preferredDistricts: ["neon_market", "cyber_hq"],
    recommendedRoles: ["trader", "code_warrior"],
    requiredCertificationMissionIds: [],
    requiredActivationCertificationMissionIds: OPERATOR_ACTIVATION_CERTS,
    team: [["trader"], ["trader", "code_warrior"], 1, 2, ["data_broker"], 0, 1],
    defense: [1, 0, 1, 0, 1, 0],
    trust: ["known", "trusted", "trusted"],
  }),
  defineBusinessVariant({
    id: "black_market_stall",
    name: "Black Market Stall",
    sector: "retail_business",
    requiresBusinessNft: true,
    minLevel: 30,
    minimumRankTier: "gold",
    minimumReputationScore: 220,
    maximumHeatScore: null,
    requiredStakingTier: "district_operator",
    requiredMilestones: DISTRICT_MILESTONES,
    allowedDistricts: ["dark_alley"],
    preferredDistricts: ["dark_alley"],
    recommendedRoles: ["hacker", "data_broker"],
    requiredCertificationMissionIds: [],
    requiredActivationCertificationMissionIds: OPERATOR_ACTIVATION_CERTS,
    team: [["hacker"], ["hacker", "data_broker"], 2, 2, ["data_broker"], 0, 1],
    defense: [2, 0, 1, 0, 2, 0, ["hacker", "data_broker"], ["hacker", "data_broker"]],
    trust: ["trusted", "elevated", "elevated"],
  }),
  defineBusinessVariant({
    id: "data_hub",
    name: "Data Hub",
    sector: "tech_startup",
    requiresBusinessNft: true,
    minLevel: 25,
    minimumRankTier: "silver",
    minimumReputationScore: 250,
    maximumHeatScore: 40,
    requiredStakingTier: "district_operator",
    requiredMilestones: DISTRICT_MILESTONES,
    allowedDistricts: ["cyber_hq", "neon_market"],
    preferredDistricts: ["cyber_hq"],
    recommendedRoles: ["data_broker", "code_warrior"],
    requiredCertificationMissionIds: DEFI_CERTS,
    requiredActivationCertificationMissionIds: OPERATOR_ACTIVATION_CERTS,
    team: [["data_broker"], ["data_broker", "code_warrior"], 2, 2, ["code_warrior", "trader"], 0, 2],
    defense: [1, 0, 2, 0, 1, 0, ["data_broker", "code_warrior"], ["data_broker", "code_warrior"]],
    trust: ["trusted", "trusted", "elevated", DEFI_CERTS, DEFI_CERTS, DEFI_CERTS],
  }),
  defineBusinessVariant({
    id: "bot_lab",
    name: "Bot Lab",
    sector: "tech_startup",
    requiresBusinessNft: true,
    minLevel: 28,
    minimumRankTier: "silver",
    minimumReputationScore: 220,
    maximumHeatScore: 45,
    requiredStakingTier: "district_operator",
    requiredMilestones: DISTRICT_MILESTONES,
    allowedDistricts: ["cyber_hq"],
    preferredDistricts: ["cyber_hq"],
    recommendedRoles: ["code_warrior", "data_broker"],
    requiredCertificationMissionIds: [],
    requiredActivationCertificationMissionIds: OPERATOR_ACTIVATION_CERTS,
    team: [["code_warrior"], ["code_warrior", "data_broker"], 2, 3, ["data_broker"], 0, 2],
    defense: [1, 0, 2, 0, 1, 0, ["code_warrior", "data_broker"], ["code_warrior", "data_broker"]],
    trust: ["trusted", "trusted", "elevated"],
  }),
  defineBusinessVariant({
    id: "signal_center",
    name: "Signal Center",
    sector: "tech_startup",
    requiresBusinessNft: true,
    minLevel: 27,
    minimumRankTier: "silver",
    minimumReputationScore: 200,
    maximumHeatScore: 45,
    requiredStakingTier: "district_operator",
    requiredMilestones: DISTRICT_MILESTONES,
    allowedDistricts: ["cyber_hq", "neon_market"],
    preferredDistricts: ["cyber_hq"],
    recommendedRoles: ["data_broker", "trader"],
    requiredCertificationMissionIds: DEFI_CERTS,
    requiredActivationCertificationMissionIds: OPERATOR_ACTIVATION_CERTS,
    team: [["data_broker"], ["data_broker", "trader"], 2, 2, ["code_warrior"], 0, 1],
    defense: [1, 0, 2, 0, 1, 0, ["data_broker", "code_warrior"], ["data_broker", "trader"]],
    trust: ["trusted", "trusted", "elevated", DEFI_CERTS, DEFI_CERTS, DEFI_CERTS],
  }),
  defineBusinessVariant({
    id: "security_office",
    name: "Security Office",
    sector: "tech_startup",
    requiresBusinessNft: true,
    minLevel: 30,
    minimumRankTier: "gold",
    minimumReputationScore: 240,
    maximumHeatScore: 40,
    requiredStakingTier: "district_operator",
    requiredMilestones: ADVANCED_MILESTONES,
    allowedDistricts: ["cyber_hq", "neon_market"],
    preferredDistricts: ["cyber_hq"],
    recommendedRoles: ["code_warrior", "data_broker"],
    requiredCertificationMissionIds: DEFI_CERTS,
    requiredActivationCertificationMissionIds: OPERATOR_ACTIVATION_CERTS,
    team: [["code_warrior"], ["code_warrior", "data_broker"], 2, 3, ["data_broker"], 0, 1],
    defense: [2, 1, 2, 1, 2, 0, ["code_warrior", "data_broker"], ["code_warrior", "data_broker"]],
    trust: ["elevated", "elevated", "elevated", DEFI_CERTS, DEFI_CERTS, DEFI_CERTS],
  }),
  defineBusinessVariant({
    id: "club",
    name: "Club",
    sector: "entertainment_venue",
    requiresBusinessNft: true,
    minLevel: 26,
    minimumRankTier: "silver",
    minimumReputationScore: 140,
    maximumHeatScore: 60,
    requiredStakingTier: "district_operator",
    requiredMilestones: DISTRICT_MILESTONES,
    allowedDistricts: ["dark_alley", "neon_market"],
    preferredDistricts: ["dark_alley"],
    recommendedRoles: ["trader", "hacker"],
    requiredCertificationMissionIds: [],
    requiredActivationCertificationMissionIds: OPERATOR_ACTIVATION_CERTS,
    team: [["trader"], ["trader", "hacker"], 2, 2, ["data_broker"], 0, 2],
    defense: [1, 0, 1, 0, 2, 0, ["data_broker"], ["trader", "hacker"]],
    trust: ["known", "trusted", "trusted"],
  }),
  defineBusinessVariant({
    id: "music_lounge",
    name: "Music Lounge",
    sector: "entertainment_venue",
    requiresBusinessNft: true,
    minLevel: 25,
    minimumRankTier: "bronze",
    minimumReputationScore: 120,
    maximumHeatScore: 55,
    requiredStakingTier: "starter_business",
    requiredMilestones: BASIC_MILESTONES,
    allowedDistricts: ["neon_market", "dark_alley"],
    preferredDistricts: ["neon_market"],
    recommendedRoles: ["trader", "data_broker"],
    requiredCertificationMissionIds: [],
    requiredActivationCertificationMissionIds: OPERATOR_ACTIVATION_CERTS,
    team: [["trader"], ["trader", "data_broker"], 1, 2, ["data_broker"], 0, 1],
    defense: [1, 0, 1, 0, 1, 0, ["data_broker"], ["trader", "data_broker"]],
    trust: ["known", "known", "trusted"],
  }),
  defineBusinessVariant({
    id: "event_hall",
    name: "Event Hall",
    sector: "entertainment_venue",
    requiresBusinessNft: true,
    minLevel: 30,
    minimumRankTier: "gold",
    minimumReputationScore: 220,
    maximumHeatScore: 45,
    requiredStakingTier: "city_operator",
    requiredMilestones: ADVANCED_MILESTONES,
    allowedDistricts: ["neon_market", "cyber_hq"],
    preferredDistricts: ["neon_market"],
    recommendedRoles: ["trader", "data_broker"],
    requiredCertificationMissionIds: [],
    requiredActivationCertificationMissionIds: OPERATOR_ACTIVATION_CERTS,
    team: [["trader"], ["trader", "data_broker"], 2, 3, ["data_broker"], 1, 2],
    defense: [1, 0, 2, 0, 2, 0, ["data_broker", "code_warrior"], ["trader", "code_warrior"]],
    trust: ["trusted", "trusted", "elevated"],
  }),
  defineBusinessVariant({
    id: "streaming_studio",
    name: "Streaming Studio",
    sector: "entertainment_venue",
    requiresBusinessNft: true,
    minLevel: 27,
    minimumRankTier: "silver",
    minimumReputationScore: 180,
    maximumHeatScore: 45,
    requiredStakingTier: "district_operator",
    requiredMilestones: DISTRICT_MILESTONES,
    allowedDistricts: ["cyber_hq", "neon_market"],
    preferredDistricts: ["cyber_hq"],
    recommendedRoles: ["data_broker", "trader"],
    requiredCertificationMissionIds: [],
    requiredActivationCertificationMissionIds: OPERATOR_ACTIVATION_CERTS,
    team: [["data_broker"], ["data_broker", "trader"], 2, 2, ["code_warrior"], 0, 1],
    defense: [1, 0, 2, 0, 1, 0, ["data_broker", "code_warrior"], ["data_broker", "trader"]],
    trust: ["known", "trusted", "trusted"],
  }),
  defineBusinessVariant({
    id: "garage",
    name: "Garage",
    sector: "manufacturing_unit",
    requiresBusinessNft: true,
    minLevel: 25,
    minimumRankTier: "silver",
    minimumReputationScore: 100,
    maximumHeatScore: 60,
    requiredStakingTier: "starter_business",
    requiredMilestones: BASIC_MILESTONES,
    allowedDistricts: ["neon_market", "cyber_hq"],
    preferredDistricts: ["cyber_hq", "neon_market"],
    recommendedRoles: ["code_warrior", "trader"],
    requiredCertificationMissionIds: [],
    requiredActivationCertificationMissionIds: OPERATOR_ACTIVATION_CERTS,
    team: [["code_warrior"], ["code_warrior", "trader"], 1, 2, ["trader", "data_broker"], 0, 2],
    defense: [1, 0, 1, 0, 1, 0],
    trust: ["known", "trusted", "trusted"],
  }),
  defineBusinessVariant({
    id: "repair_shop",
    name: "Repair Shop",
    sector: "manufacturing_unit",
    requiresBusinessNft: true,
    minLevel: 24,
    minimumRankTier: "bronze",
    minimumReputationScore: 90,
    maximumHeatScore: 55,
    requiredStakingTier: "starter_business",
    requiredMilestones: BASIC_MILESTONES,
    allowedDistricts: ["neon_market", "cyber_hq"],
    preferredDistricts: ["neon_market"],
    recommendedRoles: ["code_warrior", "trader"],
    requiredCertificationMissionIds: [],
    requiredActivationCertificationMissionIds: OPERATOR_ACTIVATION_CERTS,
    team: [["code_warrior"], ["code_warrior", "trader"], 1, 2, ["trader"], 0, 1],
    defense: [1, 0, 1, 0, 1, 0],
    trust: ["known", "known", "trusted"],
  }),
  defineBusinessVariant({
    id: "mod_shop",
    name: "Mod Shop",
    sector: "manufacturing_unit",
    requiresBusinessNft: true,
    minLevel: 28,
    minimumRankTier: "silver",
    minimumReputationScore: 160,
    maximumHeatScore: 55,
    requiredStakingTier: "district_operator",
    requiredMilestones: DISTRICT_MILESTONES,
    allowedDistricts: ["cyber_hq", "neon_market"],
    preferredDistricts: ["cyber_hq"],
    recommendedRoles: ["code_warrior", "trader"],
    requiredCertificationMissionIds: [],
    requiredActivationCertificationMissionIds: OPERATOR_ACTIVATION_CERTS,
    team: [["code_warrior"], ["code_warrior", "trader"], 2, 2, ["data_broker"], 0, 1],
    defense: [1, 0, 1, 0, 2, 0, ["code_warrior"], ["trader", "code_warrior"]],
    trust: ["trusted", "trusted", "elevated"],
  }),
  defineBusinessVariant({
    id: "workshop",
    name: "Workshop",
    sector: "manufacturing_unit",
    requiresBusinessNft: true,
    minLevel: 30,
    minimumRankTier: "gold",
    minimumReputationScore: 180,
    maximumHeatScore: 50,
    requiredStakingTier: "district_operator",
    requiredMilestones: ADVANCED_MILESTONES,
    allowedDistricts: ["cyber_hq", "dark_alley"],
    preferredDistricts: ["cyber_hq"],
    recommendedRoles: ["code_warrior", "data_broker"],
    requiredCertificationMissionIds: [],
    requiredActivationCertificationMissionIds: OPERATOR_ACTIVATION_CERTS,
    team: [["code_warrior"], ["code_warrior", "data_broker"], 2, 3, ["trader"], 0, 1],
    defense: [2, 0, 1, 0, 2, 0, ["code_warrior", "data_broker"], ["code_warrior", "trader"]],
    trust: ["trusted", "trusted", "elevated"],
  }),
  defineBusinessVariant({
    id: "bank_branch",
    name: "Bank Branch",
    sector: "financial_institution",
    requiresBusinessNft: true,
    minLevel: 30,
    minimumRankTier: "gold",
    minimumReputationScore: 260,
    maximumHeatScore: 35,
    requiredStakingTier: "city_operator",
    requiredMilestones: ADVANCED_MILESTONES,
    allowedDistricts: ["neon_market", "cyber_hq"],
    preferredDistricts: ["neon_market"],
    recommendedRoles: ["trader", "data_broker"],
    requiredCertificationMissionIds: DEFI_CERTS,
    requiredActivationCertificationMissionIds: OPERATOR_ACTIVATION_CERTS,
    team: [["trader"], ["trader", "data_broker"], 2, 2, ["data_broker"], 1, 2],
    defense: [1, 0, 2, 0, 2, 0, ["data_broker", "code_warrior"], ["trader", "code_warrior"]],
    trust: ["trusted", "trusted", "elevated", DEFI_CERTS, DEFI_CERTS, DEFI_CERTS],
  }),
  defineBusinessVariant({
    id: "exchange_desk",
    name: "Exchange Desk",
    sector: "financial_institution",
    requiresBusinessNft: true,
    minLevel: 27,
    minimumRankTier: "silver",
    minimumReputationScore: 200,
    maximumHeatScore: 45,
    requiredStakingTier: "district_operator",
    requiredMilestones: DISTRICT_MILESTONES,
    allowedDistricts: ["neon_market", "cyber_hq"],
    preferredDistricts: ["neon_market"],
    recommendedRoles: ["trader", "data_broker"],
    requiredCertificationMissionIds: DEFI_CERTS,
    requiredActivationCertificationMissionIds: OPERATOR_ACTIVATION_CERTS,
    team: [["trader"], ["trader", "data_broker"], 2, 2, ["data_broker"], 0, 1],
    defense: [1, 0, 1, 0, 1, 0, ["data_broker"], ["trader", "data_broker"]],
    trust: ["trusted", "trusted", "elevated", DEFI_CERTS, DEFI_CERTS, DEFI_CERTS],
  }),
  defineBusinessVariant({
    id: "treasury_office",
    name: "Treasury Office",
    sector: "financial_institution",
    requiresBusinessNft: true,
    minLevel: 30,
    minimumRankTier: "gold",
    minimumReputationScore: 280,
    maximumHeatScore: 35,
    requiredStakingTier: "city_operator",
    requiredMilestones: ADVANCED_MILESTONES,
    allowedDistricts: ["cyber_hq"],
    preferredDistricts: ["cyber_hq"],
    recommendedRoles: ["data_broker", "trader"],
    requiredCertificationMissionIds: DEFI_CERTS,
    requiredActivationCertificationMissionIds: OPERATOR_ACTIVATION_CERTS,
    team: [["data_broker"], ["data_broker", "trader"], 2, 3, ["code_warrior"], 1, 2],
    defense: [2, 1, 2, 1, 2, 0, ["data_broker", "code_warrior"], ["trader", "code_warrior"]],
    trust: ["elevated", "elevated", "elevated", DEFI_CERTS, DEFI_CERTS, DEFI_CERTS],
  }),
  defineBusinessVariant({
    id: "lending_hall",
    name: "Lending Hall",
    sector: "financial_institution",
    requiresBusinessNft: true,
    minLevel: 28,
    minimumRankTier: "silver",
    minimumReputationScore: 220,
    maximumHeatScore: 40,
    requiredStakingTier: "district_operator",
    requiredMilestones: DISTRICT_MILESTONES,
    allowedDistricts: ["neon_market", "cyber_hq"],
    preferredDistricts: ["neon_market", "cyber_hq"],
    recommendedRoles: ["trader", "data_broker"],
    requiredCertificationMissionIds: DEFI_CERTS,
    requiredActivationCertificationMissionIds: OPERATOR_ACTIVATION_CERTS,
    team: [["trader"], ["trader", "data_broker"], 2, 2, ["data_broker"], 0, 1],
    defense: [1, 0, 1, 0, 2, 0, ["data_broker"], ["trader", "code_warrior"]],
    trust: ["trusted", "trusted", "elevated", DEFI_CERTS, DEFI_CERTS, DEFI_CERTS],
  }),
];
